# -*- coding: utf-8 -*-
"""hw2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14d3VAyeAdVT4vM_5NPIeKeYyb5sQxv3F
"""

nameList=[] # list for names of students also this list defined for dictionary's keys
gradeList=[] # list for marks of students also this list defined for dictionary's values
info={}
m=0
n=3

for i in range(5):
  fullname=input("Name - Surname:")
  nameList.append(fullname)
  midterm=int(input("Midterm:"))
  homework=int(input("Homework:"))
  final=int(input("Final:"))
  gradeList.append(midterm)
  gradeList.append(homework)
  gradeList.append(final)


for j in range(5): # this loop for namelist and gradelist convert to dictionary
  info[nameList[j]]=gradeList[m:n]
  m=m+3
  n=n+3

list=[] # a list for average of mark
for i in range(5):
  average=0
  for j in range(3):
    average+=info[nameList[i]][j]
  score=average/3
  list.append(score)
a=0
highest=list[0] 
for k in range(1,5): #this loop for find highest average
  
  if list[k] > highest:
    highest=list[k]
    a=k
print(info)
print("Congratulations!! "+nameList[a])