# -*- coding: utf-8 -*-
"""hw3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14d3VAyeAdVT4vM_5NPIeKeYyb5sQxv3F
"""

list1=[] # list for numbers between 0-500 
list2=[] # list for numbers between 500-1000

for i in range(1001):
  if i<=500:
    list1.append(i) # add numbers between 0-500 to list
    if i==500: # if i=500 prime_first funciton is called
      prime_first(list1)
  else:
    list2.append(i) # add numbers between 500-1000 to list
      
    if i==1000: # if i=1000 prime_second funciton is called
      prime_second(list2)


primenumbers_1=[] # list for prime numbers between 0-500
primenumbers_2=[] # list for prime numbers between 500-1000
def prime_first(list1):
  for i in range(len(list1)+1):
    if i>1:
      for j in range(2,i):
       if i % j == 0: # Check for prime 
           break 
      else:
        primenumbers_1.append(i)
  print("prime numbers between 0-500:")
  for a in range(len(primenumbers_1)): # loop for print prime numbers
    print(primenumbers_1[a])
   

def prime_second(list2):
  for i in range(list2[0],list2[-1]):
    for  j in  range(2,i):
      if i % j == 0: # check for prime
        break
    else:
      primenumbers_2.append(i)
  print("prime numbers between 500-1000:")
  for a in range(len(primenumbers_2)): # loop for print prime numbers
    print(primenumbers_2[a])