# -*- coding: utf-8 -*-
"""hw4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14d3VAyeAdVT4vM_5NPIeKeYyb5sQxv3F
"""

class Hangman:
  def __init__(self):
    self.word="python" # this secret word
    self.turns=10 #player have 10 turns
    self.guesses=''
  

  def Play(self):
      # Create a while loop 

  #check if the turns are more than zero
    while self.turns > 0:  


      # make a counter that starts with zero

      failed=0
                     

      # for every character in secret word    
      for char in self.word:      

      # see if the character is in the players guess
          if char in self.guesses:    
      
          # print then out the character
              print(char)    

          else:
      
          # if not found, print a dash
              print("_")     
        
          # and increase the failed counter with one
              failed += 1    

      # if failed is equal to zero

      # print You Won
      if failed == 0:        
          print("You won")  

      # exit the script
          break              

      print()

      # ask the user go guess a character
      guess =input("guess a character:") 

      # set the players guess to guesses
      self.guesses += guess                    

      # if the guess is not found in the secret word
      if guess not in self.word:  
  
      # turns counter decreases with 1 (now 9)
          self.turns -= 1        
  
      # print wrong
          print("Wrong")
    
  
      # how many turns are left
          print("You have", + self.turns, 'more guesses')
  
      # if the turns are equal to zero
          if self.turns == 0:           
      
          # print "You Lose"
              print("You Lose")

if __name__ == '__main__':

  player=input("What is your name? ")
  print("Hello, " + player, "! Time to play hangman!")
  HM=Hangman()
  HM.Play()